#pragma once
enum BEINGOBJ_ID { BEING_PLAYER, BEING_MONSTER, BEING_MONSTERBULLET, BEING_END };
enum NOTBEINGOBJ_ID { NOTBEING_LINE, NOTBEING_BLOCK, NOTBEING_ITEM, NOTBEING_END };

enum MONSTER_TYPE { M_Cloud_TURTLE , WARRIOR_TURTLE , BOSS_KOOPA , MONSTER_END };

enum UI_STATE { STATE_PAUSE, STATE_START , STATE_GAME, STATE_OVER, STATE_END };