#pragma once
enum BEINGOBJ_ID { BEING_PLAYER, BEING_MONSTER, BEING_GOMUFISTOL, BEING_GIGNATFISTOL, BEING_MONSTERBULLET, BEING_COUNTERBULLET, BEING_END };

enum NOTBEINGOBJ_ID { NOTBEING_LINE, NOTBEING_PORTAL,  NOTBEING_WALL, NOTBEING_ITEM, NOTBEING_TRAP,NOTBEING_LADDER, NOTBEING_ROOM, ITEM_KEY, NOTBEING_BLOCK, NOTBEING_END };

enum MONSTER_TYPE { M_Cloud_TURTLE , WARRIOR_TURTLE , BOSS_KOOPA , MONSTER_END };

enum UI_STATE { STATE_PAUSE, STATE_START , STATE_GAME, STATE_OVER, STATE_END };

enum ITEM_TYPE { ITEM_GUN, ITEM_LIFE, ITEM_LADDER, ITEM_RECOVERY, ITEM_STAMINA, ITEM_BOX,  ITEM_END};